# Generated by Django 4.1.1 on 2022-09-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founders',
            name='img',
            field=models.ImageField(default='founders/person.jpeg', null=True, upload_to='founders'),
        ),
    ]
