# Generated by Django 4.1.1 on 2022-09-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_alter_founders_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founders',
            old_name='img',
            new_name='photo',
        ),
    ]
