# Generated by Django 4.1.1 on 2022-09-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_rename_img_founders_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.EmailField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('comments', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create'],
            },
        ),
    ]
