# Generated by Django 4.1.1 on 2022-09-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='comments',
            new_name='message',
        ),
    ]
