# Generated by Django 4.1 on 2022-09-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0006_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('p1', models.TextField()),
                ('p2', models.TextField()),
                ('p3', models.TextField()),
                ('p4', models.TextField()),
                ('p5', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=100)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create'],
            },
        ),
    ]
