# Generated by Django 4.1 on 2022-09-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0007_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(default='images/test.jpeg', null=True, upload_to='post_photo'),
        ),
    ]
