# Generated by Django 4.1.1 on 2022-09-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0008_post_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='founders',
            name='status',
            field=models.CharField(choices=[('coach', 'Coach'), ('player', 'Player'), ('photographer', 'Photographer'), ('founder', 'Founder')], default='player', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(default='post_photo/DSC07477.jpg', null=True, upload_to='post_photo'),
        ),
    ]
