# Generated by Django 4.1.1 on 2022-09-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0009_founders_status_alter_post_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='founders',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
