# Generated by Django 4.1.1 on 2022-09-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0010_founders_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='founders',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
