# Generated by Django 4.1.1 on 2022-09-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0011_founders_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='founders',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
