# Generated by Django 4.1.1 on 2022-09-09 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0012_founders_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founders',
            name='slug',
        ),
    ]
