# Generated by Django 4.1.1 on 2022-09-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0013_remove_founders_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='founders',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
