# Generated by Django 4.1.1 on 2022-09-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0016_post_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contact', models.CharField(max_length=250)),
                ('email_contact', models.EmailField(max_length=254)),
                ('text_contact', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded'),
        ),
    ]
