# Generated by Django 4.1.1 on 2022-09-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0017_contactus_alter_post_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='email_contact',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='name_contact',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='text_contact',
            new_name='textarea',
        ),
    ]
