# Generated by Django 4.1.1 on 2022-09-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0018_rename_email_contact_contactus_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='textarea',
            new_name='messages',
        ),
    ]
