# Generated by Django 4.1.1 on 2022-09-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0019_rename_textarea_contactus_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='messages',
            new_name='message',
        ),
    ]
