# Generated by Django 4.2.4 on 2024-01-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0021_rename_contactus_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_href',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
