# Generated by Django 4.2.4 on 2024-01-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0022_post_link_href_post_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
