# Generated by Django 4.2.4 on 2024-01-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0023_remove_post_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Founders',
        ),
    ]
