# Generated by Django 4.2.4 on 2024-02-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0024_delete_founders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='p1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='p2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='p3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='p4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='p5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
